// Code generated by Gelt; DO NOT EDIT.
package main

import (
	routes "basic/routes"
	username "basic/routes/_username"
	posts "basic/routes/posts"
	id "basic/routes/posts/_id"
	analytics "basic/routes/posts/_id/analytics"
	create "basic/routes/posts/create"
	profile "basic/routes/profile"
)

var PageRegistry = map[string]any{
	"index":            routes.Page{},
	"post_analytics":   analytics.Page{},
	"post_create":      create.Page{},
	"post_details":     id.Page{},
	"post_list":        posts.Page{},
	"profile":          profile.Page{},
	"user_by_username": username.Page{},
}
